import re

html_template = """<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><title>Planificador Semanal</title><style>@import url('https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,600;0,700;1,400&family=Inter:wght@300;400;500;600;700&display=swap');
@page { size: A4; margin: 2cm 2.5cm; }
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Inter', sans-serif; color: #2C2C2C; line-height: 1.7; background: #fff; font-size: 11pt; }
h1, h2, h3, h4 { font-family: 'Playfair Display', serif; line-height: 1.3; }

/* Cover */
.cover { page-break-after: always; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 100vh; text-align: center; background: linear-gradient(135deg, #2D4A3E 0%, #1a3a2e 100%); color: #fff; padding: 60px 40px; }
.cover h1 { font-size: 42pt; margin-bottom: 16px; }
.cover .subtitle { font-size: 16pt; color: #A3BF99; font-style: italic; margin-bottom: 40px; }
.cover .author { font-size: 12pt; color: rgba(255,255,255,0.7); margin-top: 20px; }
.cover .brand { font-size: 10pt; color: rgba(255,255,255,0.5); margin-top: 8px; letter-spacing: 2px; text-transform: uppercase; }

/* Intro pages */
.intro { page-break-after: always; padding: 40px 0; }
.intro h2 { font-size: 22pt; color: #2D4A3E; margin-bottom: 16px; }
.intro p { margin-bottom: 12px; color: #444; }
.intro ul { margin-left: 20px; margin-bottom: 16px; }
.intro li { margin-bottom: 6px; }

/* Chapter header */
.chapter-header { page-break-before: always; page-break-after: always; display: flex; flex-direction: column; align-items: center; justify-content: center; min-height: 50vh; text-align: center; background: #f5f0e8; padding: 60px; }
.chapter-header h2 { font-size: 28pt; color: #2D4A3E; margin-bottom: 8px; }

/* Planner specific */
.week-plan { page-break-inside: avoid; margin-bottom: 24px; padding-top: 10px; }
.week-plan h3 { font-size: 14pt; color: #2D4A3E; margin-bottom: 4px; }
.week-plan .portion-info { font-size: 11pt; color: #7C9A72; font-style: italic; margin-bottom: 12px; font-weight: 600; }
.plan-table { width: 100%; border-collapse: collapse; font-size: 9pt; }
.plan-table th { background: #2D4A3E; color: #fff; padding: 8px; text-align: left; }
.plan-table td { padding: 8px; border: 1px solid #e0ddd5; vertical-align: top; }
.plan-table tr:nth-child(even) { background: #faf8f4; }
.shopping-list { columns: 2; column-gap: 28px; list-style: none; }
.shopping-list li { padding: 3px 0; font-size: 9.5pt; break-inside: avoid; border-bottom: 1px dotted #ccc; }
.shopping-list li::before { content: '☐'; color: #2D4A3E; margin-right: 8px; font-size: 12pt; }

/* Footer */
.book-footer { text-align: center; padding: 40px 0; color: #999; font-size: 9pt; page-break-before: always; }
</style></head><body><div class="cover"><h1>Planificador Semanal de Comidas</h1><div class="subtitle">Organizá tus almuerzos y cenas de toda la semana</div><div class="brand">Cocina Liviana y Saludable</div></div><div class="intro"><h2>Cómo usar este planificador</h2><p>Este planificador te propone 4 semanas completas de almuerzos y cenas saludables. <strong>Primero encontrarás las 4 semanas calculadas para 1 persona</strong>, y luego <strong>las mismas 4 semanas calculadas para 2 personas</strong>.</p><p>Cada semana incluye su lista de compras exacta para que vayas al super una sola vez.</p><p><strong>Importante:</strong> Este planificador es flexible. Podés adaptarlo a tus gustos, cambiar los días o incluso hacer una combinación de 2 recetas por comida si una te parece poco para tus necesidades energéticas.</p><p><strong>Tips de batch cooking:</strong></p><ul><li>Cociná granos (quinoa, arroz integral) en cantidad los domingos</li><li>Lavá y cortá todas las verduras apenas llegues del super</li><li>Prepará aderezos y salsas para toda la semana</li><li>Congelá porciones individuales de sopas y guisos</li></ul></div>

<!-- SECCION 1 PERSONA -->
<div class="chapter-header"><h2>Planificación Semanal</h2><p style="font-size: 14pt; color: #7C9A72; font-weight: 600;">(Cantidades para 1 Persona)</p></div>

<div class="week-plan"><h3>Semana 1</h3><div class="portion-info">Para 1 Persona</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Ensalada César Liviana</td><td>Sopa de tomate y albahaca</td></tr><tr><td><strong>Martes</strong></td><td>Buddha Bowl de Quinoa</td><td>Omelette de champiñones</td></tr><tr><td><strong>Miércoles</strong></td><td>Pollo al limón con hierbas</td><td>Merluza al limón con ensalada</td></tr><tr><td><strong>Jueves</strong></td><td>Pasta integral con pesto</td><td>Tortilla de vegetales al horno</td></tr><tr><td><strong>Viernes</strong></td><td>Poke Bowl de Salmón</td><td>Crema de calabaza y jengibre</td></tr><tr><td><strong>Sábado</strong></td><td>Milanesas de pollo al horno</td><td>Ensalada tibia de quinoa</td></tr><tr><td><strong>Domingo</strong></td><td>Pollo al curry con vegetales</td><td>Sopa de lentejas</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (1 Persona)</h4><ul class="shopping-list"><li>1kg pechuga de pollo</li><li>400g salmón</li><li>2 filetes merluza</li><li>300g quinoa</li><li>200g fideos integrales</li><li>2 paltas</li><li>Lechuga romana y rúcula</li><li>Tomates (1kg)</li><li>Pepino</li><li>Champiñones 200g</li><li>Espinaca (500g)</li><li>Calabaza (1kg)</li><li>Batata (500g)</li><li>Limones (6)</li><li>Lentejas (300g)</li><li>Garbanzos (400g)</li><li>Yogur natural</li><li>Parmesano</li><li>Aceite de oliva</li><li>Salsa de soja</li><li>Avena (200g)</li><li>Huevos (1 docena)</li></ul></div>
<div class="week-plan" style="page-break-before: always;"><h3>Semana 2</h3><div class="portion-info">Para 1 Persona</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Bowl mexicano de porotos</td><td>Revuelto de espárragos y huevo</td></tr><tr><td><strong>Martes</strong></td><td>Ensalada mediterránea</td><td>Crema de brócoli</td></tr><tr><td><strong>Miércoles</strong></td><td>Pollo salteado al wok</td><td>Ensalada de pollo y palta</td></tr><tr><td><strong>Jueves</strong></td><td>Risotto de hongos</td><td>Shakshuka</td></tr><tr><td><strong>Viernes</strong></td><td>Bowl de atún y arroz</td><td>Sopa Thai de coco</td></tr><tr><td><strong>Sábado</strong></td><td>Hamburguesas de carne y avena</td><td>Ensalada de espinaca y frutillas</td></tr><tr><td><strong>Domingo</strong></td><td>Cazuela de lentejas con calabaza</td><td>Zapallitos rellenos con carne</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (1 Persona)</h4><ul class="shopping-list"><li>500g pechuga de pollo</li><li>400g carne picada magra</li><li>2 latas atún</li><li>Porotos negros (400g)</li><li>Lentejas (300g)</li><li>Arroz integral (300g)</li><li>Huevos (1 docena)</li><li>Espárragos</li><li>Brócoli</li><li>Espinaca (500g)</li><li>Champiñones (400g)</li><li>Calabaza (800g)</li><li>Zapallitos (4)</li><li>Tomates (1kg)</li><li>Palta (2)</li><li>Frutillas (200g)</li><li>Morrón rojo y verde</li><li>Leche de coco (400ml)</li><li>Garbanzos (400g)</li><li>Queso feta</li><li>Mozzarella</li></ul></div>
<div class="week-plan" style="page-break-before: always;"><h3>Semana 3</h3><div class="portion-info">Para 1 Persona</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Ensalada de quinoa y vegetales asados</td><td>Tortilla española de papas</td></tr><tr><td><strong>Martes</strong></td><td>Wrap de pollo y palta</td><td>Sopa de pollo con verduras</td></tr><tr><td><strong>Miércoles</strong></td><td>Salmón teriyaki con pak choi</td><td>Omelette de claras con verduras</td></tr><tr><td><strong>Jueves</strong></td><td>Stir-fry de carne y brócoli</td><td>Crema de espinaca</td></tr><tr><td><strong>Viernes</strong></td><td>Bowl de garbanzos al curry</td><td>Puré de papas con pollo desmenuzado</td></tr><tr><td><strong>Sábado</strong></td><td>Tarta de espinaca y ricotta</td><td>Ensalada griega</td></tr><tr><td><strong>Domingo</strong></td><td>Albóndigas de pollo en salsa</td><td>Gazpacho andaluz</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (1 Persona)</h4><ul class="shopping-list"><li>500g pechuga de pollo</li><li>300g pollo picado</li><li>2 filetes salmón</li><li>300g bife</li><li>Quinoa (200g)</li><li>Garbanzos (400g)</li><li>Huevos (1 docena)</li><li>Papas (1kg)</li><li>Espinaca (700g)</li><li>Brócoli</li><li>Pak choi o acelga</li><li>Tomates (1.5kg)</li><li>Pepino (2)</li><li>Morrón (2)</li><li>Cebolla morada</li><li>Palta (2)</li><li>Ricotta (250g)</li><li>Queso feta</li><li>Aceite de oliva y sésamo</li><li>Salsa de soja</li><li>Curry en polvo</li><li>Leche de coco</li></ul></div>
<div class="week-plan" style="page-break-before: always;"><h3>Semana 4</h3><div class="portion-info">Para 1 Persona</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Ensalada de brócoli crudo y semillas</td><td>Crema de hongos y tomillo</td></tr><tr><td><strong>Martes</strong></td><td>Bowl de tofu crocante</td><td>Sopa de zapallo y puerro</td></tr><tr><td><strong>Miércoles</strong></td><td>Pechuga rellena de espinaca</td><td>Ceviche de pescado blanco</td></tr><tr><td><strong>Jueves</strong></td><td>Fideos de arroz con verduras</td><td>Chili vegano de porotos</td></tr><tr><td><strong>Viernes</strong></td><td>Tacos de carne con guacamole</td><td>Ensalada waldorf saludable</td></tr><tr><td><strong>Sábado</strong></td><td>Lomo a la mostaza con vegetales</td><td>Minestrone</td></tr><tr><td><strong>Domingo</strong></td><td>Brochettes de pollo y vegetales</td><td>Berenjenas a la parmesana light</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (1 Persona)</h4><ul class="shopping-list"><li>500g pechuga de pollo</li><li>300g lomo</li><li>300g carne picada</li><li>400g pescado blanco</li><li>250g tofu firme</li><li>Porotos negros y colorados</li><li>Fideos de arroz (200g)</li><li>Quinoa (150g)</li><li>Brócoli (2)</li><li>Espinaca (500g)</li><li>Zapallo (800g)</li><li>Puerro (2)</li><li>Berenjenas (3)</li><li>Champiñones (400g)</li><li>Morrón (3)</li><li>Tomates (1.5kg)</li><li>Paltas (3)</li><li>Manzanas verdes (2)</li><li>Ricotta y mozzarella</li><li>Tortillas de maíz</li><li>Limas (4)</li><li>Semillas mixtas</li></ul></div>

<!-- SECCION 2 PERSONAS -->
<div class="chapter-header"><h2>Planificación Semanal</h2><p style="font-size: 14pt; color: #7C9A72; font-weight: 600;">(Cantidades para 2 Personas)</p></div>

<div class="week-plan"><h3>Semana 1</h3><div class="portion-info">Para 2 Personas</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Ensalada César Liviana</td><td>Sopa de tomate y albahaca</td></tr><tr><td><strong>Martes</strong></td><td>Buddha Bowl de Quinoa</td><td>Omelette de champiñones</td></tr><tr><td><strong>Miércoles</strong></td><td>Pollo al limón con hierbas</td><td>Merluza al limón con ensalada</td></tr><tr><td><strong>Jueves</strong></td><td>Pasta integral con pesto</td><td>Tortilla de vegetales al horno</td></tr><tr><td><strong>Viernes</strong></td><td>Poke Bowl de Salmón</td><td>Crema de calabaza y jengibre</td></tr><tr><td><strong>Sábado</strong></td><td>Milanesas de pollo al horno</td><td>Ensalada tibia de quinoa</td></tr><tr><td><strong>Domingo</strong></td><td>Pollo al curry con vegetales</td><td>Sopa de lentejas</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (2 Personas)</h4><ul class="shopping-list"><li>2kg pechuga de pollo</li><li>800g salmón</li><li>4 filetes merluza</li><li>600g quinoa</li><li>400g fideos integrales</li><li>4 paltas</li><li>Lechuga romana y rúcula</li><li>Tomates (2kg)</li><li>2 Pepinos</li><li>Champiñones 400g</li><li>Espinaca (1kg)</li><li>Calabaza (2kg)</li><li>Batata (1kg)</li><li>Limones (12)</li><li>Lentejas (600g)</li><li>Garbanzos (800g)</li><li>Yogur natural (2 potes)</li><li>Parmesano</li><li>Aceite de oliva</li><li>Salsa de soja</li><li>Avena (400g)</li><li>Huevos (2 docenas)</li></ul></div>
<div class="week-plan" style="page-break-before: always;"><h3>Semana 2</h3><div class="portion-info">Para 2 Personas</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Bowl mexicano de porotos</td><td>Revuelto de espárragos y huevo</td></tr><tr><td><strong>Martes</strong></td><td>Ensalada mediterránea</td><td>Crema de brócoli</td></tr><tr><td><strong>Miércoles</strong></td><td>Pollo salteado al wok</td><td>Ensalada de pollo y palta</td></tr><tr><td><strong>Jueves</strong></td><td>Risotto de hongos</td><td>Shakshuka</td></tr><tr><td><strong>Viernes</strong></td><td>Bowl de atún y arroz</td><td>Sopa Thai de coco</td></tr><tr><td><strong>Sábado</strong></td><td>Hamburguesas de carne y avena</td><td>Ensalada de espinaca y frutillas</td></tr><tr><td><strong>Domingo</strong></td><td>Cazuela de lentejas con calabaza</td><td>Zapallitos rellenos con carne</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (2 Personas)</h4><ul class="shopping-list"><li>1kg pechuga de pollo</li><li>800g carne picada magra</li><li>4 latas atún</li><li>Porotos negros (800g)</li><li>Lentejas (600g)</li><li>Arroz integral (600g)</li><li>Huevos (2 docenas)</li><li>Espárragos (2 atados)</li><li>Brócoli (2)</li><li>Espinaca (1kg)</li><li>Champiñones (800g)</li><li>Calabaza (1.6kg)</li><li>Zapallitos (8)</li><li>Tomates (2kg)</li><li>Palta (4)</li><li>Frutillas (400g)</li><li>Morrón rojo (2) y verde (2)</li><li>Leche de coco (800ml)</li><li>Garbanzos (800g)</li><li>Queso feta</li><li>Mozzarella</li></ul></div>
<div class="week-plan" style="page-break-before: always;"><h3>Semana 3</h3><div class="portion-info">Para 2 Personas</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Ensalada de quinoa y vegetales asados</td><td>Tortilla española de papas</td></tr><tr><td><strong>Martes</strong></td><td>Wrap de pollo y palta</td><td>Sopa de pollo con verduras</td></tr><tr><td><strong>Miércoles</strong></td><td>Salmón teriyaki con pak choi</td><td>Omelette de claras con verduras</td></tr><tr><td><strong>Jueves</strong></td><td>Stir-fry de carne y brócoli</td><td>Crema de espinaca</td></tr><tr><td><strong>Viernes</strong></td><td>Bowl de garbanzos al curry</td><td>Puré de papas con pollo desmenuzado</td></tr><tr><td><strong>Sábado</strong></td><td>Tarta de espinaca y ricotta</td><td>Ensalada griega</td></tr><tr><td><strong>Domingo</strong></td><td>Albóndigas de pollo en salsa</td><td>Gazpacho andaluz</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (2 Personas)</h4><ul class="shopping-list"><li>1kg pechuga de pollo</li><li>600g pollo picado</li><li>4 filetes salmón</li><li>600g bife</li><li>Quinoa (400g)</li><li>Garbanzos (800g)</li><li>Huevos (2 docenas)</li><li>Papas (2kg)</li><li>Espinaca (1.4kg)</li><li>Brócoli (2)</li><li>Pak choi o acelga (2 atados)</li><li>Tomates (3kg)</li><li>Pepino (4)</li><li>Morrón (4)</li><li>Cebolla morada (2)</li><li>Palta (4)</li><li>Ricotta (500g)</li><li>Queso feta</li><li>Aceite de oliva y sésamo</li><li>Salsa de soja</li><li>Curry en polvo</li><li>Leche de coco (2 latas)</li></ul></div>
<div class="week-plan" style="page-break-before: always;"><h3>Semana 4</h3><div class="portion-info">Para 2 Personas</div><table class="plan-table"><tr><th>Día</th><th>Almuerzo</th><th>Cena</th></tr><tr><td><strong>Lunes</strong></td><td>Ensalada de brócoli crudo y semillas</td><td>Crema de hongos y tomillo</td></tr><tr><td><strong>Martes</strong></td><td>Bowl de tofu crocante</td><td>Sopa de zapallo y puerro</td></tr><tr><td><strong>Miércoles</strong></td><td>Pechuga rellena de espinaca</td><td>Ceviche de pescado blanco</td></tr><tr><td><strong>Jueves</strong></td><td>Fideos de arroz con verduras</td><td>Chili vegano de porotos</td></tr><tr><td><strong>Viernes</strong></td><td>Tacos de carne con guacamole</td><td>Ensalada waldorf saludable</td></tr><tr><td><strong>Sábado</strong></td><td>Lomo a la mostaza con vegetales</td><td>Minestrone</td></tr><tr><td><strong>Domingo</strong></td><td>Brochettes de pollo y vegetales</td><td>Berenjenas a la parmesana light</td></tr></table><h4 style="margin:16px 0 8px;color:#2D4A3E;">🛒 Lista de Compras (2 Personas)</h4><ul class="shopping-list"><li>1kg pechuga de pollo</li><li>600g lomo</li><li>600g carne picada</li><li>800g pescado blanco</li><li>500g tofu firme</li><li>Porotos negros y colorados</li><li>Fideos de arroz (400g)</li><li>Quinoa (300g)</li><li>Brócoli (4)</li><li>Espinaca (1kg)</li><li>Zapallo (1.6kg)</li><li>Puerro (4)</li><li>Berenjenas (6)</li><li>Champiñones (800g)</li><li>Morrón (6)</li><li>Tomates (3kg)</li><li>Paltas (6)</li><li>Manzanas verdes (4)</li><li>Ricotta y mozzarella</li><li>Tortillas de maíz (2 paquetes)</li><li>Limas (8)</li><li>Semillas mixtas</li></ul></div>

<div class="book-footer"><p>© 2026 Cocina Liviana y Saludable</p></div></body></html>
"""

with open("assets/ebooks/bono1-planificador.html", "w", encoding="utf-8") as f:
    f.write(html_template)
print("Updated bono1-planificador.html successfully.")
